### ISSUE TITLE
AlcapDAQ Merlin Scripts incompatible when running g4sim as well

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#251]
The AlcapDAQ script crashes with the following error when running g4sim jobs are also running on Merlin:

```
Traceback (most recent call last):
  File "./run_production.py", line 216, in <module>
    while len(mu.submitted_jobs()) < nproc:
  File "/gpfs/home/edmonds_a/AlcapDAQ/analyzer/batch/jobscripts/merlin_utils.py", line 109, in submitted_jobs
    tokens[time_loc]))
  File "/gpfs/home/edmonds_a/AlcapDAQ/analyzer/batch/jobscripts/SGEJob.py", line 48, in __init__
    raise UnknownProductionError(prog)
AlCapExceptions.UnknownProductionError: AlCap Error: "Unknown production type! ('g4sim')"!
```

For the time being I can run sequentially but this should be solved in the future.

**Comment by jrquirk** [comment]
I have an idea of how to fix this, adding something like `_SIMULATION` to [SGEJob](https://github.com/alcap-org/AlcapDAQ/blob/develop/analyzer/batch/jobscripts/SGEJob.py) and appending it to the list of valid programs. The way the system counts running jobs would also need to be changed.

I'll do this next week/week after if that's okay.

**Comment by AndrewEdmonds11** [comment]
Cool. That's fine. I have a workaround for the time being so there's no rush
